const studyData = {
    maths: {
        "8": {
            "c8-ch1": { name: "Chapter 1: Rational Numbers", topics: ["Introduction", "Properties of Rational Numbers", "Representation on the Number Line", "Rational Numbers between Two Rational Numbers"] },
            "c8-ch2": { name: "Chapter 2: Linear Equations in One Variable", topics: ["Solving Equations (Linear Expressions on one Side)", "Applications", "Solving Equations (Variable on both Sides)", "Reducing Equations to Simpler Form", "Equations Reducible to the Linear Form"] },
            "c8-ch3": { name: "Chapter 3: Understanding Quadrilaterals", topics: ["Polygons", "Sum of Measures of Exterior Angles", "Kinds of Quadrilaterals", "Some Special Parallelograms"] },
            "c8-ch4": { name: "Chapter 4: Data Handling", topics: ["Organising Data", "Grouping Data", "Circle Graph or Pie Chart", "Chance and Probability"] },
            "c8-ch5": { name: "Chapter 5: Squares and Square Roots", topics: ["Properties of Square Numbers", "Finding the Square of a Number", "Square Roots", "Square Roots of Decimals", "Estimating Square Root"] },
            "c8-ch6": { name: "Chapter 6: Cubes and Cube Roots", topics: ["Cubes", "Cube Roots"] },
            "c8-ch7": { name: "Chapter 7: Comparing Quantities", topics: ["Ratios and Percentages", "Increase or Decrease Per cent", "Discounts, Profit and Loss", "Sales Tax/VAT/GST", "Compound Interest", "Applications of Compound Interest"] },
            "c8-ch8": { name: "Chapter 8: Algebraic Expressions and Identities", topics: ["Expressions, Terms, Factors, Coefficients", "Monomials, Binomials, Polynomials", "Addition and Subtraction", "Multiplication of Expressions", "What is an Identity?", "Standard Identities"] },
            "c8-ch9": { name: "Chapter 9: Mensuration", topics: ["Area of a Trapezium", "Area of a General Quadrilateral", "Area of a Polygon", "Surface Area of Cuboid, Cube, Cylinder", "Volume of Cuboid, Cube, Cylinder", "Volume and Capacity"] },
            "c8-ch10": { name: "Chapter 10: Exponents and Powers", topics: ["Powers with Negative Exponents", "Laws of Exponents", "Use of Exponents in Standard Form"] },
            "c8-ch11": { name: "Chapter 11: Direct and Inverse Proportions", topics: ["Direct Proportion", "Inverse Proportion"] },
            "c8-ch12": { name: "Chapter 12: Factorisation", topics: ["What is Factorisation?", "Method of Common Factors", "Factorisation by Regrouping Terms", "Factorisation using Identities", "Division of Algebraic Expressions"] },
            "c8-ch13": { name: "Chapter 13: Introduction to Graphs", topics: ["Bar Graph, Pie Graph, Histogram", "A Line Graph", "Linear Graphs", "Coordinates"] },
        },
        "9": {
            "c9-ch1": { name: "Chapter 1: Number Systems", topics: ["Irrational Numbers", "Real Numbers and their Decimal Expansions", "Representing Real Numbers on the Number Line", "Operations on Real Numbers", "Laws of Exponents for Real Numbers"] },
            "c9-ch2": { name: "Chapter 2: Polynomials", topics: ["Polynomials in One Variable", "Zeroes of a Polynomial", "Factorisation of Polynomials", "Algebraic Identities"] },
            "c9-ch3": { name: "Chapter 3: Coordinate Geometry", topics: ["Cartesian System", "Plotting a Point in the Plane"] },
            "c9-ch4": { name: "Chapter 4: Linear Equations in Two Variables", topics: ["Linear Equations", "Solution of a Linear Equation", "Graph of a Linear Equation in Two Variables", "Equations of Lines Parallel to x-axis and y-axis"] },
            "c9-ch5": { name: "Chapter 5: Introduction to Euclid's Geometry", topics: ["Euclid's Definitions, Axioms and Postulates", "Equivalent Versions of Euclid's Fifth Postulate"] },
            "c9-ch6": { name: "Chapter 6: Lines and Angles", topics: ["Basic Terms and Definitions", "Intersecting Lines and Non-intersecting Lines", "Pairs of Angles", "Parallel Lines and a Transversal", "Lines Parallel to the Same Line", "Angle Sum Property of a Triangle"] },
            "c9-ch7": { name: "Chapter 7: Triangles", topics: ["Congruence of Triangles", "Criteria for Congruence of Triangles", "Some Properties of a Triangle", "Some More Criteria for Congruence", "Inequalities in a Triangle"] },
            "c9-ch8": { name: "Chapter 8: Quadrilaterals", topics: ["Angle Sum Property of a Quadrilateral", "Types of Quadrilaterals", "Properties of a Parallelogram", "Another Condition for a Quadrilateral to be a Parallelogram", "The Mid-point Theorem"] },
            "c9-ch9": { name: "Chapter 9: Circles", topics: ["Circles and its Related Terms", "Angle Subtended by a Chord at a Point", "Perpendicular from the Centre to a Chord", "Circle through Three Points", "Equal Chords and their Distances from the Centre", "Angle Subtended by an Arc of a Circle", "Cyclic Quadrilaterals"] },
            "c9-ch10": { name: "Chapter 10: Heron's Formula", topics: ["Area of a Triangle – by Heron's Formula", "Application of Heron's Formula in finding Areas of Quadrilaterals"] },
            "c9-ch11": { name: "Chapter 11: Surface Areas and Volumes", topics: ["Surface Area of a Cuboid and a Cube", "Surface Area of a Right Circular Cylinder", "Surface Area of a Right Circular Cone", "Surface Area of a Sphere", "Volume of a Cuboid", "Volume of a Cylinder", "Volume of a Right Circular Cone", "Volume of a Sphere"] },
            "c9-ch12": { name: "Chapter 12: Statistics", topics: ["Collection of Data", "Presentation of Data", "Graphical Representation of Data", "Measures of Central Tendency"] },
        },
        "10": {
            "c10-ch1": { name: "Chapter 1: Real Numbers", topics: ["Euclid's Division Lemma", "The Fundamental Theorem of Arithmetic", "Revisiting Irrational Numbers", "Revisiting Rational Numbers and Their Decimal Expansions"] },
            "c10-ch2": { name: "Chapter 2: Polynomials", topics: ["Geometrical Meaning of the Zeroes of a Polynomial", "Relationship between Zeroes and Coefficients of a Polynomial"] },
            "c10-ch3": { name: "Chapter 3: Pair of Linear Equations in Two Variables", topics: ["Graphical Method of Solution", "Algebraic Methods of Solving", "Substitution Method", "Elimination Method", "Cross-Multiplication Method", "Equations Reducible to a Pair of Linear Equations"] },
            "c10-ch4": { name: "Chapter 4: Quadratic Equations", topics: ["Quadratic Equations Overview", "Factoring Methods", "Completing the Square", "Roots and Their Nature"] },
            "c10-ch5": { name: "Chapter 5: Arithmetic Progressions", topics: ["Introduction to AP", "Finding Terms", "Sum of Series"] },
            "c10-ch6": { name: "Chapter 6: Triangles", topics: ["Triangle Similarity", "Congruence Criteria", "Area Relations", "Pythagoras Theorem"] },
            "c10-ch7": { name: "Chapter 7: Coordinate Geometry", topics: ["Distance Calculation", "Section Formula", "Triangle Area"] },
            "c10-ch8": { name: "Chapter 8: Introduction to Trigonometry", topics: ["Basic Ratios", "Special Angles", "Complementary Angles", "Trigonometric Identities"] },
            "c10-ch9": { name: "Chapter 9: Some Applications of Trigonometry", topics: ["Heights and Distances"] },
            "c10-ch10": { name: "Chapter 10: Circles", topics: ["Tangent to a Circle", "Number of Tangents from a Point on a Circle"] },
            "c10-ch11": { name: "Chapter 11: Surface Areas and Volumes", topics: ["Surface Area of a Combination of Solids", "Volume of a Combination of Solids", "Conversion of Solid from One Shape to Another", "Frustum of a Cone"] },
            "c10-ch12": { name: "Chapter 12: Statistics", topics: ["Mean of Grouped Data", "Mode of Grouped Data", "Median of Grouped Data", "Graphical Representation of Cumulative Frequency Distribution"] },
            "c10-ch13": { name: "Chapter 13: Probability", topics: ["Probability — A Theoretical Approach"] },
        },
        "11": {
            "c11-ch1": { name: "Chapter 1: Sets", topics: ["Sets and their Representations", "The Empty Set", "Finite and Infinite Sets", "Equal Sets", "Subsets", "Power Set", "Universal Set", "Venn Diagrams", "Operations on Sets", "Complement of a Set", "Practical Problems on Union and Intersection"] },
            "c11-ch2": { name: "Chapter 2: Relations and Functions", topics: ["Cartesian Product of Sets", "Relations", "Functions"] },
            "c11-ch3": { name: "Chapter 3: Trigonometric Functions", topics: ["Angles", "Trigonometric Functions", "Trigonometric Functions of Sum and Difference of Two Angles", "Trigonometric Equations"] },
            "c11-ch4": { name: "Chapter 4: Complex Numbers and Quadratic Equations", topics: ["Complex Numbers", "Algebra of Complex Numbers", "The Modulus and the Conjugate", "Argand Plane and Polar Representation", "Quadratic Equations"] },
            "c11-ch5": { name: "Chapter 5: Linear Inequalities", topics: ["Inequalities", "Algebraic Solutions of Linear Inequalities in One Variable", "Graphical Solution of Linear Inequalities in Two Variables", "Solution of System of Linear Inequalities in Two Variables"] },
            "c11-ch6": { name: "Chapter 6: Permutations and Combinations", topics: ["Fundamental Principle of Counting", "Permutations", "Combinations"] },
            "c11-ch7": { name: "Chapter 7: Binomial Theorem", topics: ["Introduction to Binomial Theorem", "Applications of Binomial Theorem"] },
            "c11-ch8": { name: "Chapter 8: Sequences and Series", topics: ["Introduction to Sequences", "Types of Series", "Arithmetic Progression", "Geometric Progression", "Special Series"] },
            "c11-ch9": { name: "Chapter 9: Straight Lines", topics: ["Concept of Slope", "Equation of a Line", "Distance Formula"] },
            "c11-ch10": { name: "Chapter 10: Conic Sections", topics: ["Introduction to Conic Sections", "Properties of Circles", "Parabola Overview", "Ellipse Overview", "Hyperbola Overview"] },
            "c11-ch11": { name: "Chapter 11: Introduction to Three Dimensional Geometry", topics: ["Coordinate Axes and Coordinate Planes in Three Dimensional Space", "Coordinates of a Point in Space", "Distance between Two Points", "Section Formula"] },
            "c11-ch12": { name: "Chapter 12: Limits and Derivatives", topics: ["Intuitive Idea of Derivatives", "Limits", "Limits of Trigonometric Functions", "Derivatives"] },
            "c11-ch13": { name: "Chapter 13: Statistics", topics: ["Measures of Dispersion", "Range", "Mean Deviation", "Variance and Standard Deviation", "Analysis of Frequency Distributions"] },
            "c11-ch14": { name: "Chapter 14: Probability", topics: ["Random Experiments", "Event", "Axiomatic Approach to Probability"] },
        },
        "12": {
            "c12-ch1": { name: "Chapter 1: Relations and Functions", topics: ["Types of Relations", "Types of Functions", "Composition of Functions and Invertible Function"] },
            "c12-ch2": { name: "Chapter 2: Inverse Trigonometric Functions", topics: ["Basic Concepts", "Properties of Inverse Trigonometric Functions"] },
            "c12-ch3": { name: "Chapter 3: Matrices", topics: ["Matrix", "Types of Matrices", "Operations on Matrices", "Transpose of a Matrix", "Invertible Matrices"] },
            "c12-ch4": { name: "Chapter 4: Determinants", topics: ["Determinant", "Properties of Determinants", "Area of a Triangle", "Minors and Cofactors", "Adjoint and Inverse of a Matrix", "Applications of Determinants and Matrices"] },
            "c12-ch5": { name: "Chapter 5: Continuity and Differentiability", topics: ["Continuity", "Differentiability", "Exponential and Logarithmic Functions", "Logarithmic Differentiation", "Derivatives of Functions in Parametric Forms", "Second Order Derivative", "Mean Value Theorem"] },
            "c12-ch6": { name: "Chapter 6: Application of Derivatives", topics: ["Rate of Change of Quantities", "Increasing and Decreasing Functions", "Tangents and Normals", "Approximations", "Maxima and Minima"] },
            "c12-ch7": { name: "Chapter 7: Integrals", topics: ["Integration as an Inverse Process of Differentiation", "Methods of Integration", "Integrals of Some Particular Functions", "Integration by Partial Fractions", "Integration by Parts", "Definite Integral", "Fundamental Theorem of Calculus", "Evaluation of Definite Integrals by Substitution", "Some Properties of Definite Integrals"] },
            "c12-ch8": { name: "Chapter 8: Application of Integrals", topics: ["Area under Simple Curves", "Area between Two Curves"] },
            "c12-ch9": { name: "Chapter 9: Differential Equations", topics: ["Basic Concepts", "General and Particular Solutions", "Methods of Solving First Order, First Degree Differential Equations"] },
            "c12-ch10": { name: "Chapter 10: Vector Algebra", topics: ["Some Basic Concepts", "Types of Vectors", "Addition of Vectors", "Multiplication of a Vector by a Scalar", "Product of Two Vectors"] },
            "c12-ch11": { name: "Chapter 11: Three Dimensional Geometry", topics: ["Direction Cosines and Direction Ratios of a Line", "Equation of a Line in Space", "Angle between Two Lines", "Shortest Distance between Two Lines", "Plane", "Coplanarity of Two Lines", "Angle between Two Planes", "Distance of a Point from a Plane", "Angle between a Line and a Plane"] },
            "c12-ch12": { name: "Chapter 12: Linear Programming", topics: ["Linear Programming Problem and its Mathematical Formulation", "Different Types of Linear Programming Problems"] },
            "c12-ch13": { name: "Chapter 13: Probability", topics: ["Conditional Probability", "Multiplication Theorem on Probability", "Independent Events", "Bayes's Theorem", "Random Variables and its Probability Distributions", "Binomial Distribution"] },
        },
    },
    physics: {
        "8": {
            "p8-ch11": { name: "Chapter 11: Force and Pressure", topics: ["Force: A Push or a Pull", "Forces are due to an Interaction", "Exploring Forces", "Effects of Force", "Contact Forces", "Non-contact Forces", "Pressure", "Pressure Exerted by Liquids and Gases", "Atmospheric Pressure"] },
            "p8-ch12": { name: "Chapter 12: Friction", topics: ["Force of Friction", "Factors affecting Friction", "Friction: A Necessary Evil", "Increasing and Reducing Friction", "Wheels Reduce Friction", "Fluid Friction"] },
            "p8-ch13": { name: "Chapter 13: Sound", topics: ["Sound is Produced by a Vibrating Body", "Sound Produced by Humans", "Sound Needs a Medium for Propagation", "We Hear Sound through Our Ears", "Amplitude, Time Period and Frequency", "Audible and Inaudible Sounds", "Noise and Music", "Noise Pollution"] },
            "p8-ch14": { name: "Chapter 14: Chemical Effects of Electric Current", topics: ["Do Liquids Conduct Electricity?", "Chemical Effects of Electric Current"] },
            "p8-ch15": { name: "Chapter 15: Some Natural Phenomena", topics: ["Lightning", "Charging by Rubbing", "Types of Charges and Their Interaction", "Transfer of Charge", "The Story of Lightning", "Lightning Safety", "Earthquakes"] },
            "p8-ch16": { name: "Chapter 16: Light", topics: ["What makes Things Visible", "Laws of Reflection", "Regular and Diffused Reflection", "Reflected Light Can be Reflected Again", "Multiple Images", "Sunlight — White or Coloured", "What is inside Our Eyes?", "Care of the Eyes", "Visually Impaired Persons Can Read and Write"] },
            "p8-ch17": { name: "Chapter 17: Stars and The Solar System", topics: ["The Moon", "The Stars", "Constellations", "The Solar System", "Some Other Members of the Solar System"] },
        },
        "9": {
            "p9-ch8": { name: "Chapter 8: Motion", topics: ["Describing Motion", "Measuring the Rate of Motion", "Rate of Change of Velocity", "Graphical Representation of Motion", "Equations of Motion by Graphical Method", "Uniform Circular Motion"] },
            "p9-ch9": { name: "Chapter 9: Force and Laws of Motion", topics: ["Balanced and Unbalanced Forces", "First Law of Motion", "Inertia and Mass", "Second Law of Motion", "Third Law of Motion", "Conservation of Momentum"] },
            "p9-ch10": { name: "Chapter 10: Gravitation", topics: ["Universal Law of Gravitation", "Free Fall", "Mass", "Weight", "Thrust and Pressure", "Archimedes’ Principle", "Relative Density"] },
            "p9-ch11": { name: "Chapter 11: Work and Energy", topics: ["Work", "Energy", "Forms of Energy", "Kinetic Energy", "Potential Energy", "Law of Conservation of Energy", "Rate of Doing Work"] },
            "p9-ch12": { name: "Chapter 12: Sound", topics: ["Production of Sound", "Propagation of Sound", "Characteristics of a Sound Wave", "Reflection of Sound", "Range of Hearing", "Applications of Ultrasound", "Structure of Human Ear"] },
        },
        "10": {
            "p10-ch10": { name: "Chapter 10: Light – Reflection and Refraction", topics: ["Reflection of Light", "Spherical Mirrors", "Image Formation by Spherical Mirrors", "Refraction of Light", "Refraction through a Rectangular Glass Slab", "The Refractive Index", "Refraction by Spherical Lenses", "Image Formation by Lenses", "Lens Formula and Magnification", "Power of a Lens"] },
            "p10-ch11": { name: "Chapter 11: The Human Eye and the Colourful World", topics: ["The Human Eye", "Defects of Vision and their Correction", "Refraction of Light through a Prism", "Dispersion of White Light by a Glass Prism", "Atmospheric Refraction", "Scattering of Light"] },
            "p10-ch12": { name: "Chapter 12: Electricity", topics: ["Electric Current and Circuit", "Electric Potential and Potential Difference", "Circuit Diagram", "Ohm’s Law", "Factors on which the Resistance of a Conductor Depends", "Resistance of a System of Resistors", "Heating Effect of Electric Current", "Electric Power"] },
            "p10-ch13": { name: "Chapter 13: Magnetic Effects of Electric Current", topics: ["Magnetic Field and Field Lines", "Magnetic Field due to a Current-Carrying Conductor", "Force on a Current-Carrying Conductor in a Magnetic Field", "Electric Motor", "Electromagnetic Induction", "Electric Generator", "Domestic Electric Circuits"] },
            "p10-ch14": { name: "Chapter 14: Sources of Energy", topics: ["A Good Source of Energy", "Conventional Sources of Energy", "Alternative or Non-Conventional Sources of Energy", "Environmental Consequences"] },
        },
        "11": {
            "p11-ch1": { name: "Chapter 1: Physical World", topics: ["What is physics?", "Scope and excitement of physics", "Physics, technology and society", "Fundamental forces in nature"] },
            "p11-ch2": { name: "Chapter 2: Units and Measurement", topics: ["The international system of units", "Measurement of length, mass and time", "Accuracy, precision of instruments and errors", "Significant figures", "Dimensions of physical quantities"] },
            "p11-ch3": { name: "Chapter 3: Motion in a Straight Line", topics: ["Position, path length and displacement", "Average velocity and average speed", "Instantaneous velocity and speed", "Acceleration", "Kinematic equations for uniformly accelerated motion"] },
            "p11-ch4": { name: "Chapter 4: Motion in a Plane", topics: ["Scalars and vectors", "Resolution of vectors", "Motion in a plane", "Projectile motion", "Uniform circular motion"] },
            "p11-ch5": { name: "Chapter 5: Laws of Motion", topics: ["Aristotle’s fallacy", "The law of inertia", "Newton's first, second, and third law of motion", "Conservation of momentum", "Friction", "Dynamics of circular motion"] },
            "p11-ch6": { name: "Chapter 6: Work, Energy and Power", topics: ["The work-energy theorem", "Work", "Kinetic energy", "Potential energy", "The conservation of mechanical energy", "Power", "Collisions"] },
            // Content removed due to unknown license. Please add original or properly attributed content here.
            "p11-ch7": { name: "Chapter 7: System of Particles and Rotational Motion", topics: [] },
            "p11-ch8": { name: "Chapter 8: Gravitation", topics: ["Kepler’s laws", "Universal law of gravitation", "The gravitational constant", "Acceleration due to gravity of the earth", "Gravitational potential energy", "Escape speed", "Earth satellites"] },
        },
        "12": {
            "p12-ch1": { name: "Chapter 1: Electric Charges and Fields", topics: ["Electric charge", "Conductors and insulators", "Coulomb’s law", "Forces between multiple charges", "Electric field", "Electric flux", "Gauss’s law"] },
            "p12-ch2": { name: "Chapter 2: Electrostatic Potential and Capacitance", topics: ["Electrostatic potential", "Potential due to a point charge", "Equipotential surfaces", "Dielectrics and polarisation", "Capacitors and capacitance", "The parallel plate capacitor"] },
            "p12-ch3": { name: "Chapter 3: Current Electricity", topics: ["Electric current", "Ohm’s law", "Drift of electrons and the origin of resistivity", "Temperature dependence of resistivity", "Cells, EMF, internal resistance", "Kirchhoff’s laws", "Wheatstone bridge"] },
            "p12-ch4": { name: "Chapter 4: Moving Charges and Magnetism", topics: ["Magnetic force", "Motion in a magnetic field", "Biot-Savart law", "Ampere’s circuital law", "The solenoid and the toroid", "Force between two parallel currents", "The moving coil galvanometer"] },
            "p12-ch9": { name: "Chapter 9: Ray Optics and Optical Instruments", topics: ["Reflection of light by spherical mirrors", "Refraction", "Total internal reflection", "Refraction at spherical surfaces and by lenses", "Refraction through a prism", "Optical instruments"] },
            "p12-ch10": { name: "Chapter 10: Wave Optics", topics: ["Huygens principle", "Refraction and reflection of plane waves", "Interference of light waves and Young’s experiment", "Diffraction", "Polarisation"] },
            "p12-ch14": { name: "Chapter 14: Semiconductor Electronics", topics: ["Classification of metals, conductors and semiconductors", "Intrinsic and extrinsic semiconductor", "p-n junction", "Semiconductor diode", "Junction transistor", "Digital electronics and logic gates"] },
        },
    },
};

const studentData = [
    { id: 1, name: 'Rohan', studying: ['c10-ch1', 'c10-ch2', 'c9-ch5'] },
    { id: 2, name: 'Priya', studying: ['c10-ch2', 'c8-ch1', 'c9-ch2'] },
    { id: 3, name: 'Aman', studying: ['c8-ch1', 'c8-ch3', 'c10-ch1'] },
    { id: 4, name: 'Sneha', studying: ['c9-ch1', 'c10-ch6', 'c8-ch2'] },
    { id: 5, name: 'Vikram', studying: ['c10-ch6', 'c10-ch7', 'c9-ch7'] },
    { id: 6, name: 'Nisha', studying: ['c8-ch2', 'c8-ch4', 'c9-ch8'] },
    { id: 7, name: 'Deepak', studying: ['c9-ch1', 'c9-ch3', 'c10-ch3'] },
    { id: 8, name: 'Kavita', studying: ['c10-ch4', 'c10-ch5', 'c8-ch5'] },
    { id: 9, name: 'Sahil', studying: ['c8-ch5', 'c9-ch6', 'c10-ch8'] },
    { id: 10, name: 'Anjali', studying: ['c9-ch9', 'c10-ch9', 'c10-ch10'] },
    { id: 11, name: 'Manish', studying: ['c8-ch7', 'c9-ch10', 'c10-ch11'] },
    { id: 12, name: 'Pooja', studying: ['c8-ch9', 'c9-ch11', 'c10-ch12'] },
    { id: 13, name: 'Sumit', studying: ['c8-ch11', 'c9-ch12', 'c10-ch13'] },
    { id: 14, name: 'Ritu', studying: ['c8-ch12', 'c9-ch4', 'c10-ch5'] },
    { id: 15, name: 'Amit', studying: ['c8-ch13', 'c9-ch7', 'c10-ch7'] },
    { id: 16, name: 'Arjun', studying: ['c11-ch1', 'c11-ch3', 'c12-ch2'] },
    { id: 17, name: 'Meera', studying: ['c12-ch1', 'c12-ch5', 'c11-ch2'] },
    { id: 18, name: 'Karan', studying: ['c11-ch9', 'c12-ch10', 'c11-ch12'] },
    { id: 19, name: 'Sonia', studying: ['p9-ch8', 'p9-ch9', 'c9-ch1'] },
    { id: 20, name: 'Raj', studying: ['p10-ch10', 'p10-ch12', 'c10-ch1'] },
    { id: 21, name: 'Fatima', studying: ['p12-ch1', 'p11-ch5', 'c12-ch5'] }
];
